development:
  adapter: mysql
  encoding: utf8
  database: sample_app
  pool: 5
  username: root
  password: 
test:
  adapter: mysql
  encoding: utf8
  database: sample_app
  pool: 5
  username: root
  password:
production:
  adapter: mysql
  encoding: utf8
  database: sample_app
  pool: 5
  username: root
  password:
